### ISSUE TITLE
create structure latex for a new whitepaper.

### ISSUE THREAD

**Issue by EvertonMelo** [NebulousLabs/pages#3]
migrate document .pdf to latex.

**Comment by EvertonMelo** [comment]
without justification,

It was worth emphasizing how much suggestions are not welcome.

@lukechampine

**Comment by lukechampine** [comment]
We welcome all suggestions that are coherent and actionable. Your issue references a "whitepaper" and a ".pdf" file, neither of which appear in this repository. If you articulate your issue here, maybe I can file it in the right place.

**Comment by EvertonMelo** [comment]
ok. 

Ne nuntium necare.
